spring.application.name=URL_shortner

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortner
spring.datasource.username=rishikapadia
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080